#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

# global settings
yabai -m config \
    mouse_follows_focus off \
    focus_follows_mouse off \
    window_origin_display default \
    window_placement second_child \
    window_zoom_persist on \
    window_shadow on \
    window_animation_duration 0.1 \
    window_animation_frame_rate 120 \
    window_opacity_duration 0.0 \
    active_window_opacity 1.0 \
    normal_window_opacity 0.90 \
    window_opacity on \
    insert_feedback_color 0xffd75f5f \
    split_ratio 0.50 \
    split_type auto \
    auto_balance on \
    top_padding 8 \
    bottom_padding 8 \
    left_padding 8 \
    right_padding 8 \
    window_gap 05 \
    layout bsp \
    mouse_modifier fn \
    mouse_action1 move \
    mouse_action2 resize \
    mouse_drop_action stack \
    external_bar all:20:0 \
    focus_follows_mouse autofocus \
    window_origin_display focus

yabai -m rule --add app="Lightroom Classic" opacity=1.0
yabai -m rule --add app="Settings" manage=off
yabai -m rule --add app="kap" manage=off
yabai -m rule --add app="1Password*" manage=off
yabai -m rule --add app="Creative Cloud*" manage=off
yabai -m rule --add app="Finder*" manage=off
yabai -m rule --add app="System Preferences" manage=off
yabai -m rule --add app="System Settings" manage=off
yabai -m rule --add app="Archive Utility" manage=off
yabai -m rule --add app="Activity Monitor" manage=off
yabai -m rule --add app="Finder" manage=off
yabai -m rule --add title="Open" manage=off
echo "yabai configuration loaded.."
